# Metadata for the Waqi
plugin:
    # Global plugin attributes
    type: gateway                  # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Zugriff auf Waqi WEtter Service'
        en: 'LOg Data from Waqi Service'
    maintainer: Bonze
    state: develop 
    tester: Bonze
    keywords: communication, iot
    support: 
  # documentation: 
    version: 1.0.0             # Plugin version
    sh_minversion: 1.4           # minimum shNG version to use this plugin
    multi_instance: False          # plugin supports multi instance
    classname: Waqi                # class containing the plugin
    restartable: unknown
   
plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)
    #plugin_functions: NONE

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
    #logic_parameters: NONE

# Definition of parameters to be configured in etc/plugin.yaml
parameters:
    token: 
        de: 'token'
        en: 'token'
    city: 
        de: 'Stadt von welcher die Daten stammen sollen'
        en: 'City where the data come from'
    cycle: 
        de: 'Stadt von welcher die Daten stammen sollen'
        en: 'City where the data come from'
    alarm: 
        de: 'Alarmschwelle'
        en: 'value to trigger the alarm_items'
    keys: 
        de: 'liste der Daten, die ins data item übernommen werden soll(Hauptsächlich für Widgetanzeige)'
        en: 'list of data for the widget item (data) '   
item_structs:
waqi-service: 
    stickstoffdioxide:
        name: 'no2'
        type: num
        waqi: 'no2'    
    ozon:
        name: 'o3'
        type: num
        waqi: 'o3'
    luftdruck:
        name: 'p'
        type: num
        waqi: 'p'
    feinstaub:
        name: 'pm10'
        type: num
        waqi: 'pm10'
    windgeschwindigkeit:
        name: 'wg'
        type: num
        waqi: 'wg'
    temperatur:
        name: 't'
        type: num
        waqi: 't'
    luftqualitaet:
        name: 'aqi'
        type: num
        waqi: 'aqi'
