# Metadata for the RadioInet Busch und Jäger 8216u Plugin
plugin:
    # Global plugin attributes
    type: interface                  # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Zugriff auf Busch und Jaeger Radio Inet 8216u'
        en: 'Control Busch und Jaeger Wlan Radio 8216u'
    maintainer: Bonze
    state: develop 
    tester: Bonze 
    keywords: communication, iot
    
# documentation: 
    version: 1.0.0             # Plugin version
    sh_minversion: 1.4           # minimum shNG version to use this plugin
    multi_instance: False          # plugin supports multi instance
    classname: RadioInet               # class containing the plugin
    restartable: unknown
    

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)
    #plugin_functions: NONE

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
    #logic_parameters: NONE

# Definition of parameters to be configured in etc/plugin.yaml
parameters:
    ip: 
        de: 'IP Adresse B&J  8216U'
        en: 'IP Adress of B&J  8216U'
    cycle: 
        de: 'Standart Zyklus 10'
        en: 'default cycle time 10'
    name: 
        de: 'id für die kommunikation, dient nur der identifizierung'
        en: 'id für die kommunikation, dient nur der identifizierung'