# Metadata for the ModbusTCP Plugin
plugin:
    # Global plugin attributes
    type: gateway                  # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Zugriff auf Geräte mit ModbusTCP'
        en: 'Read Write Data from MODBUS TCP Devices'
    #maintainer: 'Bonze'
    #tester: Bonze
    keywords: communication
#    documentation: 

    version: 1.0.0              # Plugin version
    sh_minversion: 1.5           # minimum shNG version to use this plugin
    multi_instance: False          # plugin supports multi instance
    classname: ModbusTCP                # class containing the plugin

# Definition of parameters to be configured in etc/plugin.yaml
# parameters:
    # device: 
        # de: 'IP Adresse des Gerätes '
        # en: 'IP Adress of the Device'
    # port: 
        # de: '502'
        # en: '502'
    # timeout: 
        # de: '10'
        # en: '10'
    # cycle: 
        # de: '5s zyklisch lesen'
        # en: 'every 5s read all ModbusTCP items '   


# item_attributes:
    #modbus_function: 'this is mandatory'