# Metadata for the Xiaomi Saugroboter
plugin:
    # Global plugin attributes
    type: gateway                  # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Zugriff auf Xiaomi Saugroboter'
        en: 'Control the Xioami Vacuum Robot'
    maintainer: Bonze
    state: develop 
    tester: Bonze, henfri
    keywords: communication, iot
    
# documentation: 
    version: 0.4.0             # Plugin version
    sh_minversion: 1.4           # minimum shNG version to use this plugin
    multi_instance: False          # plugin supports multi instance
    classname: Robvac                # class containing the plugin
    restartable: unknown
    
item_structs: #saugroboter
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)
    #item_structs: NONE

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)
    #plugin_functions: NONE

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
    #logic_parameters: NONE

# Definition of parameters to be configured in etc/plugin.yaml
parameters:
    ip: 
        de: 'IP Adresse des Roboters '
        en: 'IP Adress of the Vakuum'
    read_cycle: 
        de: 'Standart Zyklus 12'
        en: 'default cycle time 12'
    token: 
        de: 'Token für die Kommunikation'
        en: 'Token for Communication'  
